name: Auto Publish to Google Play on Release

on:
  release:
    types: [published]

jobs:
  auto-publish-google-play:
    runs-on: ubuntu-latest

    # Only run for actual releases, not pre-releases
    if: '!github.event.release.prerelease'

    steps:
      - name: Promote Internal Release to Production
        uses: kevin-david/promote-play-release@v1.0.0
        with:
          service-account-json-raw: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          package-name: com.superproductivity.superproductivity
          from-track: internal
          to-track: production
          inapp-update-priority: 3
